export interface Category {
  id: string;
  title: string;
  icon: string;
  color: string;
  description: string;
}

export interface Question {
  id: string;
  word: string;
  description: string;
  image: string;
  options: string[];
  correctAnswer: number;
  category: string;
}

export interface Sticker {
  id: string;
  name: string;
  emoji: string;
  description: string;
  unlockCondition: string;
}

export const CATEGORIES: Category[] = [
  {
    id: 'synonyms',
    title: 'Synonyms',
    icon: '🐝',
    color: '#4DD9E8',
    description: 'Find words with similar meanings',
  },
  {
    id: 'opposites',
    title: 'Opposites',
    icon: '🔄',
    color: '#6BCB77',
    description: 'Discover words with opposite meanings',
  },
  {
    id: 'riddles',
    title: 'Riddles',
    icon: '❓',
    color: '#FFD93D',
    description: 'Solve fun word puzzles',
  },
  {
    id: 'spelling',
    title: 'Spelling',
    icon: '✏️',
    color: '#4D96FF',
    description: 'Practice spelling words correctly',
  },
  {
    id: 'animals',
    title: 'Animals',
    icon: '🦁',
    color: '#6BCB77',
    description: 'Learn about animal words',
  },
  {
    id: 'space',
    title: 'Space',
    icon: '🚀',
    color: '#FFD93D',
    description: 'Explore words about space',
  },
];

export const QUESTIONS: Question[] = [
  // SYNONYMS - Words with similar meanings
  {
    id: 'syn_1',
    word: 'GIGANTIC',
    description: 'Which word means the same as GIGANTIC?',
    image: '🏔️',
    options: ['Tiny', 'Enormous', 'Narrow', 'Quiet'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_2',
    word: 'TINY',
    description: 'Which word means the same as TINY?',
    image: '🔍',
    options: ['Microscopic', 'Huge', 'Tall', 'Wide'],
    correctAnswer: 0,
    category: 'synonyms',
  },
  {
    id: 'syn_3',
    word: 'HAPPY',
    description: 'Which word means the same as HAPPY?',
    image: '🎈',
    options: ['Gloomy', 'Cheerful', 'Angry', 'Tired'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_4',
    word: 'SMART',
    description: 'Which word means the same as SMART?',
    image: '🎓',
    options: ['Foolish', 'Clever', 'Lazy', 'Slow'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_5',
    word: 'BEAUTIFUL',
    description: 'Which word means the same as BEAUTIFUL?',
    image: '🌺',
    options: ['Ugly', 'Lovely', 'Dirty', 'Plain'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_6',
    word: 'BRAVE',
    description: 'Which word means the same as BRAVE?',
    image: '🦸',
    options: ['Scared', 'Courageous', 'Weak', 'Shy'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_7',
    word: 'QUICK',
    description: 'Which word means the same as QUICK?',
    image: '⚡',
    options: ['Slow', 'Rapid', 'Heavy', 'Quiet'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_8',
    word: 'ANGRY',
    description: 'Which word means the same as ANGRY?',
    image: '💢',
    options: ['Happy', 'Mad', 'Calm', 'Sleepy'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_9',
    word: 'SHOUT',
    description: 'Which word means the same as SHOUT?',
    image: '📢',
    options: ['Whisper', 'Yell', 'Listen', 'Sleep'],
    correctAnswer: 1,
    category: 'synonyms',
  },
  {
    id: 'syn_10',
    word: 'FUNNY',
    description: 'Which word means the same as FUNNY?',
    image: '🎭',
    options: ['Sad', 'Hilarious', 'Boring', 'Serious'],
    correctAnswer: 1,
    category: 'synonyms',
  },

  // OPPOSITES - Words with opposite meanings
  {
    id: 'opp_1',
    word: 'HOT',
    description: 'What is the opposite of HOT?',
    image: '🌡️',
    options: ['Warm', 'Cold', 'Wet', 'Dry'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_2',
    word: 'HAPPY',
    description: 'What is the opposite of HAPPY?',
    image: '🎭',
    options: ['Joyful', 'Sad', 'Excited', 'Calm'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_3',
    word: 'BIG',
    description: 'What is the opposite of BIG?',
    image: '📏',
    options: ['Large', 'Small', 'Tall', 'Wide'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_4',
    word: 'LIGHT',
    description: 'What is the opposite of LIGHT?',
    image: '🌓',
    options: ['Bright', 'Dark', 'Clear', 'Shiny'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_5',
    word: 'FAST',
    description: 'What is the opposite of FAST?',
    image: '🐢',
    options: ['Quick', 'Slow', 'Loud', 'Soft'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_6',
    word: 'TALL',
    description: 'What is the opposite of TALL?',
    image: '📐',
    options: ['High', 'Short', 'Wide', 'Long'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_7',
    word: 'HARD',
    description: 'What is the opposite of HARD?',
    image: '🪨',
    options: ['Tough', 'Soft', 'Strong', 'Rough'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_8',
    word: 'CLEAN',
    description: 'What is the opposite of CLEAN?',
    image: '🧹',
    options: ['Neat', 'Dirty', 'Fresh', 'Bright'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_9',
    word: 'LOUD',
    description: 'What is the opposite of LOUD?',
    image: '🔊',
    options: ['Noisy', 'Quiet', 'Big', 'Fast'],
    correctAnswer: 1,
    category: 'opposites',
  },
  {
    id: 'opp_10',
    word: 'EMPTY',
    description: 'What is the opposite of EMPTY?',
    image: '🥤',
    options: ['Vacant', 'Full', 'Open', 'Closed'],
    correctAnswer: 1,
    category: 'opposites',
  },

  // ANIMALS - Logical questions about animals
  {
    id: 'ani_1',
    word: 'Which animal lives in water?',
    description: 'Choose the water animal',
    image: '🌊',
    options: ['Lion', 'Fish', 'Eagle', 'Rabbit'],
    correctAnswer: 1,
    category: 'animals',
  },
  {
    id: 'ani_2',
    word: 'Which animal can fly?',
    description: 'Choose the flying animal',
    image: '☁️',
    options: ['Dog', 'Cat', 'Bird', 'Horse'],
    correctAnswer: 2,
    category: 'animals',
  },
  {
    id: 'ani_3',
    word: 'Which animal is the largest?',
    description: 'Choose the biggest animal',
    image: '🌍',
    options: ['Mouse', 'Elephant', 'Rabbit', 'Squirrel'],
    correctAnswer: 1,
    category: 'animals',
  },
  {
    id: 'ani_4',
    word: 'Which animal has stripes?',
    description: 'Choose the striped animal',
    image: '🎨',
    options: ['Tiger', 'Bear', 'Cow', 'Pig'],
    correctAnswer: 0,
    category: 'animals',
  },
  {
    id: 'ani_5',
    word: 'Which animal hops?',
    description: 'Choose the hopping animal',
    image: '🦘',
    options: ['Snake', 'Fish', 'Kangaroo', 'Snail'],
    correctAnswer: 2,
    category: 'animals',
  },
  {
    id: 'ani_6',
    word: 'Which animal has a long neck?',
    description: 'Choose the long-necked animal',
    image: '🌳',
    options: ['Giraffe', 'Dog', 'Cat', 'Mouse'],
    correctAnswer: 0,
    category: 'animals',
  },
  {
    id: 'ani_7',
    word: 'Which animal lives in a hive?',
    description: 'Choose the hive animal',
    image: '🏠',
    options: ['Cow', 'Bee', 'Lion', 'Rabbit'],
    correctAnswer: 1,
    category: 'animals',
  },
  {
    id: 'ani_8',
    word: 'Which animal is nocturnal?',
    description: 'Choose the night animal',
    image: '🌙',
    options: ['Rooster', 'Owl', 'Duck', 'Chicken'],
    correctAnswer: 1,
    category: 'animals',
  },
  {
    id: 'ani_9',
    word: 'Which animal has a shell?',
    description: 'Choose the shelled animal',
    image: '🐚',
    options: ['Dog', 'Cat', 'Turtle', 'Rabbit'],
    correctAnswer: 2,
    category: 'animals',
  },
  {
    id: 'ani_10',
    word: 'Which animal has a trunk?',
    description: 'Choose the animal with a trunk',
    image: '🌴',
    options: ['Elephant', 'Monkey', 'Bear', 'Wolf'],
    correctAnswer: 0,
    category: 'animals',
  },

  // RIDDLES - Logical thinking puzzles
  {
    id: 'rid_1',
    word: 'What has hands but cannot clap?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Gloves', 'Clock', 'Tree', 'Book'],
    correctAnswer: 1,
    category: 'riddles',
  },
  {
    id: 'rid_2',
    word: 'What has keys but no locks?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Door', 'Piano', 'Car', 'House'],
    correctAnswer: 1,
    category: 'riddles',
  },
  {
    id: 'rid_3',
    word: 'What gets wet while drying?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Towel', 'Rain', 'Water', 'Sponge'],
    correctAnswer: 0,
    category: 'riddles',
  },
  {
    id: 'rid_4',
    word: 'What goes up but never comes down?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Balloon', 'Your Age', 'Airplane', 'Bird'],
    correctAnswer: 1,
    category: 'riddles',
  },
  {
    id: 'rid_5',
    word: 'What has a head and tail but no body?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Snake', 'Coin', 'Fish', 'Worm'],
    correctAnswer: 1,
    category: 'riddles',
  },
  {
    id: 'rid_6',
    word: 'What can run but never walks?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Water', 'Dog', 'Car', 'Clock'],
    correctAnswer: 0,
    category: 'riddles',
  },
  {
    id: 'rid_7',
    word: 'What has teeth but cannot bite?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Tiger', 'Comb', 'Shark', 'Alligator'],
    correctAnswer: 1,
    category: 'riddles',
  },
  {
    id: 'rid_8',
    word: 'What comes once in a minute, twice in a moment, but never in a thousand years?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Letter M', 'Time', 'Clock', 'Second'],
    correctAnswer: 0,
    category: 'riddles',
  },
  {
    id: 'rid_9',
    word: 'What has an eye but cannot see?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Blind Person', 'Needle', 'Camera', 'Telescope'],
    correctAnswer: 1,
    category: 'riddles',
  },
  {
    id: 'rid_10',
    word: 'What belongs to you but others use it more?',
    description: 'Think carefully!',
    image: '🤔',
    options: ['Shoes', 'Your Name', 'Phone', 'Chair'],
    correctAnswer: 1,
    category: 'riddles',
  },

  // SPELLING - Test correct spelling
  {
    id: 'spe_1',
    word: 'How do you spell the furry pet that meows?',
    description: 'Choose the correct spelling',
    image: '🏠',
    options: ['KAT', 'CAT', 'KET', 'CATT'],
    correctAnswer: 1,
    category: 'spelling',
  },
  {
    id: 'spe_2',
    word: 'How do you spell the furry pet that barks?',
    description: 'Choose the correct spelling',
    image: '🏠',
    options: ['DOG', 'DAG', 'DOGG', 'DOJ'],
    correctAnswer: 0,
    category: 'spelling',
  },
  {
    id: 'spe_3',
    word: 'How do you spell what you read?',
    description: 'Choose the correct spelling',
    image: '📖',
    options: ['BOKE', 'BOOK', 'BOUK', 'BUK'],
    correctAnswer: 1,
    category: 'spelling',
  },
  {
    id: 'spe_4',
    word: 'How do you spell the large plant with leaves?',
    description: 'Choose the correct spelling',
    image: '🌲',
    options: ['TREE', 'TREA', 'TREI', 'TRE'],
    correctAnswer: 0,
    category: 'spelling',
  },
  {
    id: 'spe_5',
    word: 'How do you spell the star in our sky?',
    description: 'Choose the correct spelling',
    image: '☀️',
    options: ['SAN', 'SON', 'SUN', 'SUNN'],
    correctAnswer: 2,
    category: 'spelling',
  },
  {
    id: 'spe_6',
    word: 'How do you spell the red fruit?',
    description: 'Choose the correct spelling',
    image: '🍎',
    options: ['APEL', 'APPLE', 'APLE', 'APPEL'],
    correctAnswer: 1,
    category: 'spelling',
  },
  {
    id: 'spe_7',
    word: 'How do you spell the color of grass?',
    description: 'Choose the correct spelling',
    image: '🌿',
    options: ['GREEN', 'GREN', 'GREAN', 'GRENE'],
    correctAnswer: 0,
    category: 'spelling',
  },
  {
    id: 'spe_8',
    word: 'How do you spell frozen water?',
    description: 'Choose the correct spelling',
    image: '❄️',
    options: ['ICE', 'IZE', 'ISE', 'YCE'],
    correctAnswer: 0,
    category: 'spelling',
  },
  {
    id: 'spe_9',
    word: 'How do you spell where you live?',
    description: 'Choose the correct spelling',
    image: '🏡',
    options: ['HOUS', 'HOUSE', 'HOWSE', 'HOUZ'],
    correctAnswer: 1,
    category: 'spelling',
  },
  {
    id: 'spe_10',
    word: 'How do you spell drops from clouds?',
    description: 'Choose the correct spelling',
    image: '🌧️',
    options: ['RAIN', 'RANE', 'RAYN', 'RIAN'],
    correctAnswer: 0,
    category: 'spelling',
  },

  // SPACE - Questions about space
  {
    id: 'spa_1',
    word: 'What orbits around Earth?',
    description: 'Choose the correct answer',
    image: '🌍',
    options: ['Sun', 'Moon', 'Mars', 'Jupiter'],
    correctAnswer: 1,
    category: 'space',
  },
  {
    id: 'spa_2',
    word: 'What is at the center of our solar system?',
    description: 'Choose the correct answer',
    image: '☀️',
    options: ['Earth', 'Sun', 'Moon', 'Star'],
    correctAnswer: 1,
    category: 'space',
  },
  {
    id: 'spa_3',
    word: 'What do astronauts travel in?',
    description: 'Choose the correct answer',
    image: '👨‍🚀',
    options: ['Plane', 'Car', 'Rocket', 'Boat'],
    correctAnswer: 2,
    category: 'space',
  },
  {
    id: 'spa_4',
    word: 'What is Earth?',
    description: 'Choose the correct answer',
    image: '🌎',
    options: ['Star', 'Moon', 'Planet', 'Comet'],
    correctAnswer: 2,
    category: 'space',
  },
  {
    id: 'spa_5',
    word: 'What do we see in the night sky that twinkles?',
    description: 'Choose the correct answer',
    image: '🌌',
    options: ['Planet', 'Stars', 'Moon', 'Cloud'],
    correctAnswer: 1,
    category: 'space',
  },
  {
    id: 'spa_6',
    word: 'What is the largest planet in our solar system?',
    description: 'Choose the correct answer',
    image: '🪐',
    options: ['Earth', 'Jupiter', 'Mars', 'Venus'],
    correctAnswer: 1,
    category: 'space',
  },
  {
    id: 'spa_7',
    word: 'What is the Red Planet called?',
    description: 'Choose the correct answer',
    image: '🔴',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswer: 1,
    category: 'space',
  },
  {
    id: 'spa_8',
    word: 'What protects Earth from harmful sun rays?',
    description: 'Choose the correct answer',
    image: '🛡️',
    options: ['Clouds', 'Atmosphere', 'Moon', 'Stars'],
    correctAnswer: 1,
    category: 'space',
  },
  {
    id: 'spa_9',
    word: 'What do we call a person who goes to space?',
    description: 'Choose the correct answer',
    image: '👨‍🚀',
    options: ['Pilot', 'Astronaut', 'Sailor', 'Driver'],
    correctAnswer: 1,
    category: 'space',
  },
  {
    id: 'spa_10',
    word: 'What has rings around it?',
    description: 'Choose the correct answer',
    image: '💍',
    options: ['Earth', 'Mars', 'Saturn', 'Venus'],
    correctAnswer: 2,
    category: 'space',
  },
];

// Sticker system
export const STICKERS: Sticker[] = [
  {
    id: 'welcome',
    name: 'Welcome Star',
    emoji: '⭐',
    description: 'Welcome to Word Explorer!',
    unlockCondition: 'Start the app',
  },
  {
    id: 'first_star',
    name: 'First Star',
    emoji: '🌟',
    description: 'Earned your first star!',
    unlockCondition: 'Complete first level',
  },
  {
    id: 'perfect_score',
    name: 'Perfect Score',
    emoji: '💯',
    description: 'Got 3 stars in a level!',
    unlockCondition: 'Get 3 stars',
  },
  {
    id: 'synonym_master',
    name: 'Synonym Master',
    emoji: '📖',
    description: 'Completed all synonym levels!',
    unlockCondition: 'Complete Synonyms',
  },
  {
    id: 'opposite_guru',
    name: 'Opposite Guru',
    emoji: '🔄',
    description: 'Mastered opposites!',
    unlockCondition: 'Complete Opposites',
  },
  {
    id: 'animal_friend',
    name: 'Animal Friend',
    emoji: '🦁',
    description: 'Animal expert!',
    unlockCondition: 'Complete Animals',
  },
  {
    id: 'space_explorer',
    name: 'Space Explorer',
    emoji: '🚀',
    description: 'Explored all space words!',
    unlockCondition: 'Complete Space',
  },
  {
    id: 'riddle_solver',
    name: 'Riddle Solver',
    emoji: '🧩',
    description: 'Solved all riddles!',
    unlockCondition: 'Complete Riddles',
  },
  {
    id: 'spelling_bee',
    name: 'Spelling Bee',
    emoji: '🐝',
    description: 'Spelling champion!',
    unlockCondition: 'Complete Spelling',
  },
  {
    id: 'daily_streak_3',
    name: '3 Day Streak',
    emoji: '🔥',
    description: 'Completed 3 daily words!',
    unlockCondition: '3 day streak',
  },
  {
    id: 'daily_streak_7',
    name: '7 Day Streak',
    emoji: '💪',
    description: 'One week streak!',
    unlockCondition: '7 day streak',
  },
  {
    id: 'score_500',
    name: 'Score Master',
    emoji: '🎯',
    description: 'Reached 500 points!',
    unlockCondition: 'Score 500 points',
  },
];